### ISSUE TITLE
Dúvida: tipos de cursos

### ISSUE THREAD

**Issue by juliatessler** [celycodes/cursos-gratuitos#7]
Olá! Gostaria de contribuir, mas tenho algumas dúvidas:

1. São apenas cursos ou tutoriais também valem? (Uma versão mais aberta dessa pergunta é: o que define um curso?)
2. O material pode ser em texto ao invés de vídeo?
3. São apenas tecnologias no sentido de linguagens de programação/frameworks ou é possível adicionar outras coisas (como análise de dados, por exemplo)?

**Comment by celenny** [comment]
Olá Júlia, adorei a sua issue pois, ela realmente me fez pensar em ampliar os tipos de materiais no repositório.
Vou responder a cada tópico que você mencionou:

- 1 ) Acredito que tutoriais também podem ser adicionados.
- 2 ) Vou criar uma pasta para adicionar livros e apostilas gratuitas.
- 3 ) Com certeza, você pode criar o arquivo analise-de-dados.md e adicionar o curso ou tutorial que desejar.

Muito obrigada e sinta-se à vontade para contribuir...
